FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base

WORKDIR /AdFormTodoApi

EXPOSE 80



FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

WORKDIR /AdFormTodoApi
COPY . /AdFormTodoApi


RUN dotnet restore "AdFormTodoApi/AdFormTodoApi/AdFormTodoApi.csproj"

COPY . .

WORKDIR "/AdFormTodoApi/AdFormTodoApi"

RUN dotnet build "AdFormTodoApi/AdFormTodoApi.csproj" -c Release -o /app/build



FROM build AS publish

RUN dotnet publish "AdFormTodoApi/AdFormTodoApi.csproj" -c Release -o /app/publish



FROM base AS final

WORKDIR /AdFormTodoApi

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "AdFormTodoApi.dll"]